language: go
sudo: false
go:
  - "1.10.x"
  - master

os:
  - linux
  - osx

script:
  - env GO111MODULE=on go build
  - env GO111MODULE=on go test

after_success:
  - bash <(curl -s https://codecov.io/bash)
