language: go
sudo: false
go:
  - "1.11.x"
  - master

services:
  - redis-server

os:
  - linux

script:
  - env GO111MODULE=on go build -v ./...
  - env GO111MODULE=on ops/test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
